import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";
import { ConfigProvider } from "antd";
import vinVN from "antd/locale/vi_VN";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider locale={vinVN}>{children}</ConfigProvider>
      </body>
    </html>
  );
}
